coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
# Updated 20251109_123805
# Updated Sun Nov  9 12:50:03 CET 2025
