name: Weekly Commit

on:
  schedule:
    - cron: "0 12 * * 1"  # Weekly on Monday at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  weekly-commit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create weekly contribution
        run: |
          echo "Weekly contribution: $(date +%Y-%m-%d\ %H:%M:%S)" >> weekly-activity.log
          echo "GitHub stats repository weekly activity maintained" >> weekly-activity.log
          echo "---" >> weekly-activity.log
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add weekly-activity.log
          git diff --staged --quiet || git commit -m "Weekly activity: $(date +%Y-%m-%d)"
          git push
